# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
      inputs:
        myInput:
          description: 'User Input:'
          required: true
          default: "Hello World"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
      - name: Install Python dependencies
        run: python3 -m pip install --upgrade pip plotly
      - name: Install Python dependencies
        run: python3 -m pip install --upgrade pip requests
      - name: Execute Test Script
        run: |
          echo "Store: ${{ github.event.inputs.myInput }}"
          INPUT_STORE=${{ github.event.inputs.myInput }} python3 plotting.py
          

